name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # ← ఇక్కడ 18 ని 20 చెయ్
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Angular App
        run: npm run build
      
      - name: List dist folder
        run: ls -R dist
        
      - name: Build Docker Image
        run: docker build -t gov:latest .
